[build]
#pre-build = ["xargo install rustfmt clippy"]

[target.x86_64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture amd64 && apt-get -y update; apt-get -y install libusb-1.0-0:amd64 libusb-1.0-0-dev:amd64",
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture arm64 && apt-get -y update; apt-get -y install libusb-1.0-0:arm64 libusb-1.0-0-dev:arm64",
]

[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture armhf && apt-get -y update; apt-get -y install libusb-1.0-0:armhf libusb-1.0-0-dev:armhf",
]