#!/bin/bash
## This file will be executed after the deb package was installed

set -xe

if [[ ! -e /etc/es2button/entrypoint ]]; then
    ln -s /etc/es2button/default /etc/es2button/entrypoint
    chmod +x /etc/es2button/entrypoint
fi

# reload systemd services
systemctl daemon-reload

# reload udev rules
udevadm control --reload-rules

# start all stopped es2button services
systemctl restart es2button@*.service