[target.aarch64-unknown-linux-gnu]
strip = { path = "aarch64-linux-gnu-strip" }
objcopy = { path = "aarch64-linux-gnu-objcopy" }

[target.armv7-unknown-linux-gnueabihf]
strip = { path = "arm-linux-gnueabihf-strip" }
objcopy = { path =  "arm-linux-gnueabihf-objcopy" }