on: [push, pull_request]

jobs:
  build_job:
    # The host should always be linux
    runs-on: ubuntu-latest
    name: Build on x86_64 

    steps:
      # Checkout the repo to $PWD
      - uses: actions/checkout@v3
      # Build
      - name: Build
        run: |
          sudo apt-get --quiet update -y
          sudo apt-get install -y -q wget cmake file build-essential libboost-dev nlohmann-json3-dev libusb-1.0-0 libusb-1.0-0-dev
          cmake . -B.build
          make -C .build -j2
          make -C .build package

      - uses: actions/upload-artifact@v3
        with:
          name: packages-x86_64
          path: .build/artifacts/*.deb